This could probably break stuffs, but I've almost i18n everything
git-svn-id: http://svn.aircrack-ng.org/branch/airoscript-ng@2165 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/src/functions/_internal b/src/functions/_internal
--- a/src/functions/_internal
+++ b/src/functions/_internal
@@ -17,7 +17,7 @@
 #        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
 required(){
-	check_function $1 ||  { echo "${warn}${2}"; return 1; }
+	check_function $1 ||  { specialwarn "${warn}${2}"; return 1; }
 }
 
 error(){
@@ -152,8 +152,7 @@ load_plugins(){
 }
 
 initial_warning(){
-	warn -en $mark;
-    _ "  Airoscript is provided under the gpl.
+    markwarn $"  Airoscript is provided under the gpl.
 I'm not responsible of the use anyone can give to airoscript.
 Written for educational purpose in mind.
 "
@@ -162,9 +161,12 @@ sleep $warn_time
 
 # Standard functions.
 
+markwarn(){
+	echo -e "${warn}${@}"
+}
 
 _debug(){
-    if [ "$debug" == 1 ]; then echo -en $mark; _ $1; fi
+    if [ "$debug" == 1 ]; then markwarn $1; fi
 }
 
 execute(){ 
@@ -175,7 +177,7 @@ execute(){
     if [  "$ADDOPTIONS" != "" ]; then
         printf -- "Executing $@"
         echo
-        read -p "Enter extra options to execute: " eopts
+        read -p $"Enter extra options to execute: " eopts
     fi
         if [ "$1" == "crack" ]; then HOLDA="-hold"; shift; fi # FIXME This will work just on xterm.
         if [ "$QUIET" != "" ] || [ "$AUTO" == "1" ]; then 
@@ -200,7 +202,7 @@ monmode(){ { ifconfig $1 up; $iwconfig $1 |grep "Monitor" && if [ $? != 0 ]; the
 # this function allows debugging, called from main menu.
 function debug {
 	if [ "$debug" == "1" ] || [ "$hold" == "1"  ]; then
-		export HOLD=$HOLDFLAG; _ "Debug Mode enabled, you'll have to manually close windows"
+		export HOLD=$HOLDFLAG; echo $"Debug Mode enabled, you'll have to manually close windows"
 	else export HOLD="" ;fi
 }
 
@@ -213,10 +215,10 @@ _read(){
 checkdir(){
     if [ -d $DUMP_PATH ]; then
         if [ "$DEBUG" == 1 ]; then
-            _ "[INFO] Output folder is" " $DUMP_PATH";
+            echo $"[INFO] Output folder is" " $DUMP_PATH";
         fi
     else
-        _ "[Error] Output folder does not exists or is a regular file."
+        echo $"[Error] Output folder does not exists or is a regular file."
         exit
     fi
 }
@@ -239,11 +241,7 @@ attack_wep(){
 }
 
 attack_opn(){ # If no encryption detected
-    if [ "$Host_SSID" = "" ]; then
-        $clear &&  echo  "`gettext 'ERROR: You have to select a target'`"
-    else
-        $clear && echo `gettext "ERROR: Network not encrypted or no network selected "`
-    fi
+	$clear && error "Network not encrypted or not network selected";
 }
 
 capture(){
@@ -266,7 +264,7 @@ yesno(){
 
 check_default_software(){
 	for program in ${required_software[@]}; do
-		[[ $(whereis $program) ]] || { echo "$program not found, quitting." ; exit ; } 
+		[[ $(whereis $program) ]] || { echo -en "$program"; warn "not found, quitting." ; exit ; } 
 	done
 }
 
diff --git a/src/functions/interface b/src/functions/interface
--- a/src/functions/interface
+++ b/src/functions/interface
@@ -22,12 +22,12 @@ _(){
 
 setps(){
     $clear
-    if [ "$1" != "" ]; then PS3=`_ "$1"`;
-    else PS3=`_ 'Input number: '`; fi
+    if [ "$1" != "" ]; then PS3=$"$1";
+    else PS3=$'Input number: '; fi
 }
 
 default_theme(){
-    _ '[WARN] : theme file does not exists, using defaults...'
+    markwarn $'Theme file does not exists, using defaults...\n'
 	DUMPING_COLOR="#FFFFFF"; INJECTION_COLOR="#1DFF00"
 	ASSOCIATION_COLOR="#FF0009"; DEAUTH_COLOR="#99CCFF"; BACKGROUND_COLOR="#000000"
 }
@@ -35,12 +35,12 @@ default_theme(){
 resolution() {
    { reso=$( awk '/\*/ {print $1}' <(xrandr) | head -n1; ); } &>/dev/null
     for i in ${!available_resos[@]}; do [[ ${available_resos[$i]} == $reso ]] && {  reson=$reso; pos=$i; }; done 
-    [[ $reson != "" ]] && { export resonset=1;  echo -e "${mark}Automatically setting resolution to $reso" ; }
-    xhost &>/dev/null || { echo -e "${mark}Error: Access control for X is disabled for root. Please, as your normal user execute 'xhost +`whoami`' and press enter to continue"; read ;}
+    [[ $reson != "" ]] && { export resonset=1;  markwarn $"Automatically setting resolution to $reso" ; }
+    xhost &>/dev/null || { error $"Access control for X is disabled for root. Please, as your normal user execute 'xhost +`whoami`' and press enter to continue"; read ;}
 	while true; do 
-		if [[ ${resonset} == "" ]]; then mkmenu "Resolution" ${available_resos[@]}; pos=$choice; fi
+		if [[ ${resonset} == "" ]]; then mkmenu $"Set resolution" ${available_resos[@]}; pos=$choice; fi
 	    set_resolution_data $pos
-		[[ $TLX == "" ]] && { $clear; echo "${mark}Unknown resolution, try again"; } || break;
+		[[ $TLX == "" ]] && { $clear; error $"Unknown resolution, try again"; } || break;
 	done
 }
 
@@ -82,11 +82,11 @@ mkmenuline(){ echo -en "$separator_x"; for i in $(seq 1 $1); do echo -en "$separ
 mkmenuheader(){ echo -en "\033[$(($2 / 2 - (${#1} / 2 - 10) ))C$1\n"; }
 getmaxlenfromlist(){ max=0; for i in "${@}"; do [[ ${#i} -gt $max ]] && max=${#i}; done; echo $max; }
 mkmenueline(){ echo -en "${separator_v}\033[${1}C${separator_v}\033[${1}D${white}${2}${red})${end} ${separator_v}";}
-mkmenulines(){ max=$1; shift; for i in "${@}"; do line=$(( $line + 1 )); mkmenueline $max $line; echo " $i"; done; }
+mkmenulines(){ max=$1; shift; for i in "${@}"; do line=$(( $line + 1 )); mkmenueline $max $line; echo "$i"; done; }
 
 mkmenu(){
     if [ "$AUTO" == 2 ]; then return; fi
-    [[ ${ERRORS} ]] && echo "${mark} Error: ${ERRORS[@]}"
+    [[ ${ERRORS} ]] && markwarn "Error:" "${ERRORS[@]}"
 	ERRORS=""
     max=`getmaxlenfromlist "${@}"`
     max=$(( $max + 10 ))
@@ -97,7 +97,7 @@ mkmenu(){
     mkmenulines $max "${@}"
     mkmenuline $max
 
-    echo -en "$mark`_ 'Select option:'`"
+    markwarn $"Select option:"
     set -a choice
     _read -a choice
 }
@@ -105,7 +105,6 @@ mkmenu(){
 
 
 getterminal(){
-    [[ "$TERMINAL" = "GUI" ]] && TERMINAL="airosperl"
     if [ -x $TERMBIN/$TERMINAL ]; then
 	    _debug "Using configured terminal"
 	else
@@ -123,7 +122,7 @@ getterminal(){
             if [ -x "$TERMBIN/xterm" ]; then
 				TERMINAL="xterm" && _debug "Using Xterm"
 			else
-			_   "I cant find any good terminal, please set one on your conffile
+			echo $"I cant find any good terminal, please set one on your conffile
 				Your TERMINAL var contains no valid temrinal
 				Your alternative against x-terminal-emulator contains no terminal
 				Xterm can\'t be found on your system, Maybe not in /usr/bin?"
