airmon-ng: detect if putting the card into monitor mode fails and recover by making fun of the user (bug 1613).  Minor mksh fixes, minor formatting fixes
git-svn-id: http://svn.aircrack-ng.org/trunk@2672 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/scripts/airmon-ng b/scripts/airmon-ng
--- a/scripts/airmon-ng
+++ b/scripts/airmon-ng
@@ -182,7 +182,7 @@ handleLostPhys() {
 		fi
 	done
 				#add some spacing so this doesn't make the display hard to read
-				printf "\n\n"
+				printf "\n"
 }
 
 findFreeInterface() {
@@ -276,8 +276,8 @@ rfkill_check() {
 		printf "rfkill had no output, something went wrong.\n"
 		exit 1
 	else
-		soft="$(printf \"${rfkill_status}\" | grep -i soft | awk '{print $3}')"
-		hard="$(printf \"${rfkill_status}\" | grep -i hard | awk '{print $3}')"
+		soft=$(printf "${rfkill_status}" | grep -i soft | awk '{print $3}')
+		hard=$(printf "${rfkill_status}" | grep -i hard | awk '{print $3}')
 		if [ "${soft}" = "yes" ] && [ "${hard}" = "no" ]; then
 			return 1
 		elif [ "${soft}" = "no" ] && [ "${hard}" = "yes" ]; then
@@ -457,7 +457,7 @@ setChannelMac80211() {
 		else
 			#mac80211 specific check to see if hardware supports the frequency number being assigned (requires grep with pcre)
 			if [ -r "/sys/class/net/$1/phy80211/name" ]; then
-				frequency_list="$(iw phy $(cat /sys/class/net/$1/phy80211/name) info 2>&1 | grep -oP '\*\ \K[\d]+\ MHz')"
+				frequency_list="$(iw phy $(cat /sys/class/net/$1/phy80211/name) info 2>&1 | grep -oP '\*\ \K[\d]+\ ')"
 				local hardware_valid_freq=1
 				for i in $frequency_list; do
 					if [ "${CH}" = "${i}" ]; then
@@ -480,7 +480,10 @@ setChannelMac80211() {
 	if [ -n "${IW_ERROR}" ]; then
 		printf "\nError setting channel: ${IW_ERROR}\n"
 		if printf "${IW_ERROR}" | grep -q "(-16)"; then
-			printf "This likely means your card was set back to station mode, run airmon-ng check kill\n\n"
+			printf "Error -16 likely means your card was set back to station mode by something.\n"
+			printf "Removing non-monitor interface...\n"
+			stopMac80211Iface "${1}" abort
+			exit 1
 		fi
 		if printf "${IW_ERROR}" | grep -q "(-22)"; then
 			printf "Unable to set channel/frequency ${CH}, most likely it is outside of regulatory domain\n\n"
@@ -497,26 +500,26 @@ setChannelMac80211() {
 
 stopMac80211Iface() {
 	if [ -f /sys/class/net/${1}/type ]; then
-		if [ "$(cat /sys/class/net/${1}/type)" != "803" ]; then
+		if [ "${2}" != "abort" ] && [ "$(cat /sys/class/net/${1}/type)" != "803" ]; then
 			printf "\n\nYou are trying to stop a device that isn't in monitor mode.\n"
 			printf "Doing so is a terrible idea, if you really want to do it then you\n"
 			printf "need to type 'iw ${1} del' yourself since it is a terrible idea.\n"
 			printf "Most likely you want to remove an interface called wlan[0-9]mon\n"
 			printf "If you feel you have reached this warning in error,\n"
-			printf "please report it."
+			printf "please report it.\n"
 			exit 1
 		else
 			if [ "${ELITE}" = "0" ]; then
-				#check if $1 already has a sta interface on the same phy and bail if it does
+				local need_sta=1
 				if [ -d /sys/class/ieee80211/${PHYDEV}/device/net ]; then
 					for i in $(ls /sys/class/ieee80211/${PHYDEV}/device/net/); do
 						if [ "$(cat /sys/class/ieee80211/${PHYDEV}/device/net/${i}/type)" = "1" ]; then
-							printf "\n\t\t(mac80211 station mode vif already available for [${PHYDEV}]${1} on [${PHYDEV}]${i})\n"
-							exit
+							[ "${2}" != "abort" ] && printf "\n\t\t(mac80211 station mode vif already available for [${PHYDEV}]${1} on [${PHYDEV}]${i})\n"
+							need_sta=0
 						fi
 					done
 				fi
-				if [ -e /sys/class/net/${1%mon}/phy80211/name ]; then
+				if [ "${need_sta}" = "1" ] && [ -e /sys/class/net/${1%mon}/phy80211/name ]; then
 					if [ "$(cat /sys/class/net/${1%mon}/phy80211/name)" = "${PHYDEV}" ]; then
 						printf "\nYou already have a ${1%mon} device but it is NOT in station mode."
 						printf "\nWhatever you did, don't do it again."
@@ -528,26 +531,32 @@ stopMac80211Iface() {
 						findFreeInterface station
 					fi
 				fi
-				IW_ERROR="$(iw phy ${PHYDEV} interface add ${1%mon} type station 2>&1)"
-				if [ -z "${IW_ERROR}" ]; then
-					interface="${1%mon}"
-					if [ -d /sys/class/ieee80211/${PHYDEV}/device/net ]; then
-						for i in $(ls /sys/class/ieee80211/${PHYDEV}/device/net/); do
-							if [ "$(cat /sys/class/ieee80211/${PHYDEV}/device/net/${i}/type)" = "1" ]; then
-								#here is where we catch udev renaming our interface
-								interface="${i}"
-							fi
-						done
+				if [ "${need_sta}" = "1" ]; then
+					IW_ERROR="$(iw phy ${PHYDEV} interface add ${1%mon} type station 2>&1)"
+					if [ -z "${IW_ERROR}" ]; then
+						interface="${1%mon}"
+						if [ -d /sys/class/ieee80211/${PHYDEV}/device/net ]; then
+							for i in $(ls /sys/class/ieee80211/${PHYDEV}/device/net/); do
+								if [ "$(cat /sys/class/ieee80211/${PHYDEV}/device/net/${i}/type)" = "1" ]; then
+									#here is where we catch udev renaming our interface
+									interface="${i}"
+								fi
+							done
+						fi
+						printf "\n\t\t(mac80211 station mode vif enabled on [${PHYDEV}]${interface})\n"
+					else
+						printf "\n\n ERROR adding station mode interface: ${IW_ERROR}\n"
 					fi
-					printf "\n\t\t(mac80211 station mode vif enabled on [${PHYDEV}]${interface})\n"
-				else
-					printf "\n\n ERROR adding station mode interface: ${IW_ERROR}\n"
 				fi
 			fi
 			setLink ${1} down
 			IW_ERROR="$(iw dev "${1}" del 2>&1 | grep "nl80211 not found")"
 			if [ -z "$IW_ERROR" ]; then
-				printf "\n\t\t(mac80211 monitor mode vif disabled for [${PHYDEV}]${1})\n"
+				if [ "${2}" != "abort" ]; then
+					printf "\n\t\t(mac80211 monitor mode vif disabled for [${PHYDEV}]${1})\n"
+				elif [ "${2}" = "abort" ]; then
+					printf "\nWARNING: unable to start monitor mode, please run \"airmon-ng check kill\"\n"
+				fi
 			else
 				if [ -f /sys/class/ieee80211/${PHYDEV}/remove_iface ]; then
 					printf "${1}" > /sys/class/ieee80211/${PHYDEV}/remove_iface
@@ -1255,7 +1264,7 @@ for iface in $(printf "${iface_list}"); do
 			FIELD1t="\t\t"
 		fi
 		FIELD2="${DRIVER}[${STACK}]-${FIRMWARE}"
-		if [ ${#FIELD2} -gt 27 ]; then
+		if [ ${#FIELD2} -gt 28 ]; then
 			FIELD2t="\t"
 		else
 			FIELD2t="\t\t"
