fix "cannot access /sys/class/ieee80211/: No such file or directory" properly
git-svn-id: http://svn.aircrack-ng.org/trunk@2858 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/scripts/airmon-ng b/scripts/airmon-ng
--- a/scripts/airmon-ng
+++ b/scripts/airmon-ng
@@ -168,20 +168,22 @@ usage() {
 
 handleLostPhys() {
 	MISSING_INTERFACE=""
-	for i in $(ls /sys/class/ieee80211/ 2>/dev/null); do
-		if [ ! -d /sys/class/ieee80211/${i}/device/net ]; then
-			MISSING_INTERFACE="${i}"
-			printf "\nFound ${MISSING_INTERFACE} with no interfaces assigned, would you like to assign one to it? [y/n] "
-			yesorno
-			retcode=$?
-               		if [ "${retcode}" = "1" ]; then
-				printf "PHY ${MISSING_INTERFACE} will remain lost.\n"
-			elif [ "${retcode}" = "0" ]; then
-				PHYDEV=${MISSING_INTERFACE}
-				findFreeInterface monitor
-               		fi
-		fi
-	done
+        if [ -d /sys/class/ieee80211 ]; then
+		for i in $(ls /sys/class/ieee80211/); do
+			if [ ! -d /sys/class/ieee80211/${i}/device/net ]; then
+				MISSING_INTERFACE="${i}"
+				printf "\nFound ${MISSING_INTERFACE} with no interfaces assigned, would you like to assign one to it? [y/n] "
+				yesorno
+				retcode=$?
+	               		if [ "${retcode}" = "1" ]; then
+					printf "PHY ${MISSING_INTERFACE} will remain lost.\n"
+				elif [ "${retcode}" = "0" ]; then
+					PHYDEV=${MISSING_INTERFACE}
+					findFreeInterface monitor
+	               		fi
+			fi
+		done
+	fi
 				#add some spacing so this doesn't make the display hard to read
 				printf "\n"
 }
