airmon-ng: improve lost phys support
git-svn-id: http://svn.aircrack-ng.org/trunk@2617 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/scripts/airmon-ng b/scripts/airmon-ng
--- a/scripts/airmon-ng
+++ b/scripts/airmon-ng
@@ -161,27 +161,23 @@ usage() {
 }
 
 handleLostPhys() {
-	MISSING_INTERFACES=""
+	MISSING_INTERFACE=""
 	for i in $(ls /sys/class/ieee80211/); do
 		if [ ! -d /sys/class/ieee80211/${i}/device/net ]; then
-			MISSING_INTERFACES="${MISSING_INTERFACES} ${i}"
+			MISSING_INTERFACE="${i}"
+			printf "\nFound ${MISSING_INTERFACE} with no interfaces assigned, would you like to assign one to it? [y/n] "
+			yesorno
+			retcode=$?
+               		if [ "${retcode}" = "1" ]; then
+				printf "PHY ${MISSING_INTERFACE} will remain lost.\n"
+			elif [ "${retcode}" = "0" ]; then
+				PHYDEV=${MISSING_INTERFACE}
+				findFreeInterface monitor
+               		fi
 		fi
 	done
-	if [ -n "${MISSING_INTERFACES}" ]; then
-		printf "The following phy(s) have no interfaces assigned: ${MISSING_INTERFACES}\n"
-		printf "\nWould you like to create an interface? [y/n] "
-		yesorno
-		retcode=$?
-                if [ "${retcode}" = "1" ]; then
-                        printf "PHY(s) ${MISSING_INTERFACES} will remain lost.\n\n"
-                elif [ "${retcode}" = "0" ]; then
-			for PHYDEV in ${MISSING_INTERFACES}; do
-				findFreeInterface monitor
 				#add some spacing so this doesn't make the display hard to read
 				printf "\n\n"
-			done
-                fi
-	fi
 }
 
 findFreeInterface() {
@@ -223,7 +219,8 @@ findFreeInterface() {
 						for j in $(ls /sys/class/ieee80211/${PHYDEV}/device/net/); do
 							if [ "$(cat /sys/class/ieee80211/${PHYDEV}/device/net/${j}/type)" = "${target_type}" ]; then
 								#here is where we catch udev renaming our interface
-								i=${j}
+								k=${j#wlan}
+								i=${k%mon}
 							fi
 						done
 					else
