airmon-ng: spit out actual iw error
git-svn-id: http://svn.aircrack-ng.org/trunk@2564 28c6078b-6c39-48e3-add9-af49d547ecab

diff --git a/scripts/airmon-ng b/scripts/airmon-ng
--- a/scripts/airmon-ng
+++ b/scripts/airmon-ng
@@ -240,7 +240,8 @@ startMac80211Iface() {
 		setChannelMac80211 ${1}mon
 		printf "\n\t\t(mac80211 monitor mode vif enabled for [${PHYDEV}]${1} on [${PHYDEV}]${1}mon)\n"
 	else
-		printf "\n\nERROR: something went wrong with iw."
+		printf "\n\nERROR: ${IW_ERROR}"
+		exit 1
 	fi
 	if [ ${ELITE} = "1" ]
 	then
